package lk.dialog.crm.util;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Util {
    
    
    public static boolean evaluate() {
        
        return true;
    }
    
   
   
}